# Generated by Django 5.0.2 on 2024-02-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='initial_notification_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
