# Generated by Django 5.0.2 on 2024-02-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_attendee_initial_notification_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='initial_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
